# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: akhila.gangisetty001@gmail.com
author_name: akhila
contract_name: yield_router
deployment_language: python
preset_name: starter
project_name: yield_router-contracts

